### ISSUE TITLE
ETL Code erstellen und DWH erstellen.

### ISSUE THREAD

**Issue by psokolo** [Fuenfgeld/DMA2023TeamC#10]
Anschliessend die Kopie von DWH Datei in github Repository speichern

**Comment by edjoha** [comment]
@psokolo Das ist eigentlich so weit fertig, oder?

**Comment by psokolo** [comment]
noch nicht, muss korrigiert werden

**Comment by Deronectes** [comment]
@psokolo Das ist fertig, nicht?

**Comment by psokolo** [comment]
bis auf ggf kosmetische sachen ja
