### ISSUE TITLE
ETL Prozess dokumentieren auf einer separaten Wiki Seite

### ISSUE THREAD

**Issue by psokolo** [Fuenfgeld/DMA2023TeamC#11]

**Comment by edjoha** [comment]
@Deronectes hast du dir dafür noch mal 2 neue Issues angelegt? #20 und #21? Dann könnte das hier nämlich zu, oder?

**Comment by Deronectes** [comment]
Nicht wirklich, aber vielleicht denken wir nur verschiedenen über die issues und was unter was fällt. Besser im Meeting zu klären!

**Comment by Deronectes** [comment]
ETL Seite im Wiki angelegt, link zum code ist auch eingerichtet
