### ISSUE TITLE
WIKI

### ISSUE THREAD

**Issue by psokolo** [Fuenfgeld/DMA2023TeamC#12]

**Comment by psokolo** [comment]
Sodass Wiki eigenen Hashtag hat...

**Comment by Deronectes** [comment]
Ich hab es mir angesehen, wir sollen darüber sprchen wie wir das genau wollen bevor ich beginne die pages im Sidebar zu verbinden!

**Comment by edjoha** [comment]
Ich würde sagen, angelehnt an das, was TeamA gemacht hat - Home, Projektbeschreibung, Quelldatei, DMP, Datenverarbeitung, Datenanalyse, Ergebnisse

**Comment by Deronectes** [comment]
Keine Ahnung was das A team gemacht hat, die Struktur ist allerdings nicht so ganz klar, darum eher nopch mal kurz drüber sprechen würde ich sagen

**Comment by Deronectes** [comment]
Habe mir gerade das Wiki von Team A angesehen, ja so ähnlich würde ich es auch machen, aber das mit der Einleitung würde ich durch die Projektbeschreibung erstetzen, das mit dem Datanlebenszyklus würde ich kurz einbringen, aber das mit den FAIR- Prinzipien ist eher was man dieser Tage sowieso berücksichtigen muss. Oder was meint Ihr?

**Comment by Deronectes** [comment]
Na ja, das ist eine Möglichkeit, aber ich denke es ist nicht so tirival wie
es scheint, da bei dieser Reihenfolge viele Dopplungen zu erwarten sind.
Lass uns heute nach dem Meeting sprechen.

**Comment by edjoha** [comment]
Die Sidebar ist erstmal so weit fertig, denke ich. Ich erstelle einen Milestone mit WIKI und dann können wir alles, was noch fehlt dort als einzelne Issues eintragen.
