### ISSUE TITLE
Verlinkungen prüfen

### ISSUE THREAD

**Issue by edjoha** [Fuenfgeld/DMA2023TeamC#15]
* Querverweise auf Headers
* externe Links auf Websites (SNOMED?)
* Links zu Code und Tabellen
etc.

**Comment by edjoha** [comment]
Ganz am Ende prüfen ... und auf jeder geprüften Seite kann unten das Issue verlinkt werden

**Comment by Deronectes** [comment]
@edjoha: Könntest Du bitte die noch notwendigen Links identifizieren und mitteilen! So richtig verstehe ich nicht, was Du damit meinst

**Comment by edjoha** [comment]
das machen wir ganz zum Schluss, wenn der text steht. Ist nur zur Kontrolle gedacht

**Comment by Deronectes** [comment]
OK!

**Comment by Deronectes** [comment]
ISt soweit alles funktionsfähig

**Comment by edjoha** [comment]
Lass das ruhig noch offen, dann gucken wir ganz am Ende noch mal über alles drüber

**Comment by Deronectes** [comment]
Ich denke wir werden alle nochmal durchsehen müssen, man übersieht allein einfach zuviel

**Comment by edjoha** [comment]
ich denke, ich habe alle Links wieder aktualisiert, aber wenn euch noch etwas auffällt, sagt gern Bescheid :)

**Comment by psokolo** [comment]
ich muss noch alle Code Verlinkungen überprüfen

**Comment by edjoha** [comment]
@psokolo ich habe die erste Hälfte des Wiki fertig überprüft. Von mir aus, kann das Issue also geschlossen werden

**Comment by Deronectes** [comment]
Habe ich was verpasst? Ich dachte die Überprüfung sei schon eine Weile abgeschlossen. Sorry, ich war in den letzten Tagen krank und habe nur gestern auf Max´es Anfrage reagiert. Ich habe auch die Lizenzen vor ein paar Tagen eingefügt.

**Comment by edjoha** [comment]
Nein, hast du nicht. Wir haben uns gestern eingeteilt. Und nein, das war in der Gesamtheit noch nicht abgeschlossen... ganz am Ende hatten wir doch gesagt und es wurde ja immer noch mal was eingefügt

**Comment by Deronectes** [comment]
Ich habe die Nachrichten bekommen, auch wenn ich nicht sicher bin ob ich weiss worauf sie sich jeweils bezieht, wie dem auch sei, neben dem Recovery der vorherigen Version würde ich gern wissen warum die Revisionen alle verschwunden sind, wenn es nicht umkopiert worden ist. Der Zugriff über die codes an der Seite geht schon, ist aber nicht wirklich sinnvoll, da ich es nur sehen kann, aber weder die vorherige Version wiederherstellen kann, noch wirklich mit einer anderen vergleichen kann. Leider hat Max mir nicht geantwortet als ich ihn deswegen fragte, doch vielleicht hat er einfach die Frage nicht verstanden/verstehen können. Jedenfalls ist das mit dem Versionieren und der Verfolgbarbeit nur sehr bedingt möglich, wenn die vorherigen Versionen einfach verschwinden.

**Comment by edjoha** [comment]
Ehrlich gesagt, weiß ich auch nicht genau, was du meinst ... aber das können wir uns auch gern noch mal in einem Live-Meeting anschauen. Das andere Issue zur Powerpoint kann eigentlich auch geschlossen werden, oder?

**Comment by Deronectes** [comment]
Es bezieht sich auf deinen Hinweis, dass man die "verlorenen". Versionen und Revisionen über das Anklicken der ID codes in der History wiederherstellen kann. Das sieht bei mir so aus, dass ich sie zwar sehen kann aber mehr auch nicht. Das mit den verschwundenen Revisionen ist wirklich ärgerlich, hätte man vorher wissen sollen, nicht, dass ich das für eine unnötige Funktion halte, dass auch etwas wieder verschwinden kann, nur war es hier etwas unglücklich zumal Du nichts gelöscht oder umkopiert hast. Ist also dann doch nicht so sicher was den Verlust angeht.

**Comment by psokolo** [comment]
Verlinkungen wurden überprüft und korrigiert
