### ISSUE TITLE
Verification Code hinzufügen

### ISSUE THREAD

**Issue by edjoha** [Fuenfgeld/DMA2023TeamC#17]
Codezeilen implementieren, mit denen getestet werden kann, ob der Code das ausgibt, was er sollte (ggfs. an anderen Gruppen orientieren (Tobias/Tatiana))

**Comment by psokolo** [comment]
ist bereits drin. für jede Tabelle werden die ersten 5 rows geprinted, es werden auch alle Tabellennamen in der Datenbank abgefragt

**Comment by edjoha** [comment]
perfekt!
