### ISSUE TITLE
Starschema dokumentieren

### ISSUE THREAD

**Issue by edjoha** [Fuenfgeld/DMA2023TeamC#18]
Dokumentation des Starschemas im Wiki, Auswahl der Daten

**Comment by Deronectes** [comment]
@edjoha Das ist doch bereits fertig, oder habe ich das missverstanden? Als Star- oder Snowflake....

**Comment by edjoha** [comment]
Das Schema an sich ja, aber nicht die Dokumentation. Oder steht irgendwo schon beschrieben, was es für ein Schema ist und wie alles ausgewählt wurde und zusammenhängt? Das wäre für mich Dokumentation oder brauchen wir das nicht?

**Comment by Deronectes** [comment]
@edjoha Ich habe gerade im Chat geschrieben, eine Beschreibung muss schon noch rein, ist aber nicht viel. Wichtiger ist vielleicht wo wir das ansiedeln, ohne zu viele Dopplungen entstehen!

**Comment by Deronectes** [comment]
@psokolo , @edjoha Ich habe es nun bei dem DWH angesiedelt, da es erst nach der Auswahl und Reduktion der Daten entsehen konnte und daher direkt die Stuktur der Daten im Warehouse auzeigen. Aber sind das dann immer noch Quelldaten? Irgendwie sind die Begriffe nicht ganz klar, weil abgeleitete Daten eigentlich solche sind, die erst nach Analyse entstehen. Hier entstehen ja keine Daten sondern werden nur in anderer Form aufgearbeitet und zusammengestellt????

**Comment by edjoha** [comment]
ich würde auch sagen, dass es zum DWH muss und nicht zu Quelldaten, ja (war es da vorher?...)

**Comment by edjoha** [comment]
fertig
