### ISSUE TITLE
Wiki Page Datawarehouse Star Schema einfügen

### ISSUE THREAD

**Issue by Deronectes** [Fuenfgeld/DMA2023TeamC#21]
@edjoha Könntest Du bitte das "Star Schema" in die Seite einfügen, ich habe die hier mit den Tabellen die zum Warehouse gehören zusammen assoziiert. Das Issue zum Einfügen der Tabellen ist jedoch unter Datenstruktur, weil ich es auch dort benötige, um den DMP zu vervollständigen

**Comment by edjoha** [comment]
Schema ist eingefügt. Den zweiten Satz verstehe ich nicht ...? Was meinst du damit? Soll es noch irgendwo rein?

**Comment by Deronectes** [comment]
@edjoha ich dachte Du richtest eine Seite mit dem Snowflake oder Sternschema ein!? Hmm, ich bin nicht sicher wie ich den zweiten Satz den Du nicht verstehst anders schreiben kann, besprechen wir eher im Meeting oder?

**Comment by Deronectes** [comment]
@edjoha , @psokolo Ich habe nun eine Galaxy schema als DWH schema eingefügt, bzw, es so genannt. Ok?

**Comment by psokolo** [comment]
Ja klar. ich denke für unser schema passt eh keine von diesen beschreibungen genau

**Comment by Deronectes** [comment]
Wir könnten es noch Satelieten schema nennen, gibt es glaube ich noch nicht

**Comment by Deronectes** [comment]
@edjoha nein, es geht nur um den Namen, also Star, Snowflake, ...

**Comment by edjoha** [comment]
wenn man sich das hier https://www.tutorialspoint.com/dwh/dwh_schemas.htm anschaut, würde ich immer noch denken, dass es ein Snowflake Schema ist. "Due to normalization in the Snowflake schema, the redundancy is reduced" ... das ist bei uns ja so. Und in der Abbildung hier, haben auch nicht alle Dimensionstabellen weitere Verweigerungen oder tlw nur 1. Oder @Deronectes was denkst du?

**Comment by edjoha** [comment]
die Stichpunkte könnte man zur Erklärung ja auch übernehmen

**Comment by Deronectes** [comment]
@edjoha Ist mir nicht wichtig, ich denke man kann für alles Argumente finden. Snowflake ist für mich in Ordnung, keine Ahnung ob wir dass noch begründen müssen.

**Comment by Deronectes** [comment]
Done, oder?
