### ISSUE TITLE
Fragestellung updaten

### ISSUE THREAD

**Issue by edjoha** [Fuenfgeld/DMA2023TeamC#22]
1. Fragestellung anpassen
2. Warum haben wir Fragestellung UND Hypothese?? Ist das ein Versehen?

**Comment by Deronectes** [comment]
Nein, dass ist kein Versehen. Die Fragestellung ist eine Sache und die dem Projekt vorausgehende Hypothese etwas anderes. Was wollten wir nochmal machen? Medikation, oder?

**Comment by edjoha** [comment]
Achso. Ja ich hab es schon gemacht, aber der übernimmt die Issues auf dem Wiki ja nicht. Ich schließe es wieder
