### ISSUE TITLE
Grafiken im "Code" hinterlegen und im Wiki nur als Link einfügen

### ISSUE THREAD

**Issue by edjoha** [Fuenfgeld/DMA2023TeamC#23]
@Deronectes ich habe gesehen, dass du eine Grafik zur Datenprozessierung im Wiki hast. Kannst du die bitte im "Code" hinterlegen und nur als Link einfügen, so wie das Metaheart Logo?

**Comment by edjoha** [comment]
betrifft genauso die Grafik unter "Datenmanagemantprozesse"

**Comment by edjoha** [comment]
Und genauso "Datenlebenszyklus"

**Comment by Deronectes** [comment]
@edjoha :Ich habe leider keine Ahnung was Du meinst. Der Link zu Code, Datenmanagementprozesse und Datenlebenszyklus längst da. Und was meinst Du mit "....nur als Link einfügen...."?

**Comment by edjoha** [comment]
Die Dateien an sich müssen in unser Repository "Code". Du müsstest sie also durch einen Commit dem repository hinzufügen. Oder du schickst sie mir, dann mach ich das ;). Im Wiki werden die Dateien dann nur verlinkt. Das hat was damit zu tun, dass man sie dann zentral updaten kann. Das hab ich glaube schon mal versucht zu erklären, aber vielleicht auch noch mal im Meeting besprechen?

**Comment by Deronectes** [comment]
Ja, eine gute Idee, hatte ich schon angemerkt, dass ein Meeting gut wäre. 
Ich sehe nicht, dass das im Code sein sollte und im Wiki sind ide Sachen alle verlinkt und nur wenig abgelegt. Doch das ist ersichtlich in pages und sidebar.
Ich schätze es sehr, dass Du die Verlinkung im Wiki machen willst, habe nur leider keine Ahnung was ich dir dazu schicken sollte.

**Comment by edjoha** [comment]
Vllt Schickst du mir einfach deine png Dateien und ich zeig es heute Abend nach dem allgemeinen Meeting kurz? Ich denke wir treffen uns anschließend noch mal, oder?

**Comment by edjoha** [comment]
Das was "Code" heißt ist unser Repository und da gehören alle Dateien rein. Auch Bilder, und nicht nur Code. Es geht einfach darum , wenn man die Bilder ändert, muss man sie im Wiki händisch ändern, auch wenn sie mehrfach eingefügt sind, wie das Logo. Wie gesagt, ich kann es heute Abend zeigen, was ich meine :)

**Comment by Deronectes** [comment]
Ja, ich bin heute am Abend aber vermutlich nicht verfügbar. 
Keine Ahnung ob das so stimmt, mit den Daten kann ich ja verstehen, aber Abbildungen und Text? Ich weiss, Du hattest das gesagt.

**Comment by Deronectes** [comment]
Ich habe das jetzt mal ausprobiert, leider ist die Verlinkung mit den Abbildungen in der CODE sektion nicht wirklich befriedigend. Ich habe es wieder reverted.

**Comment by Deronectes** [comment]
Wie gesagt der Link funktioniert nicht wirklich und im Wiki möächte man vielleicht keinen Link zur "Arbeitsversion". Vielleicht gibt es noch eine andere Lösung

**Comment by edjoha** [comment]
das sah aber aus, als hätte es funktioniert ...🤔

**Comment by Deronectes** [comment]
Hmm, sehe ich nicht

**Comment by edjoha** [comment]
Das Datenprozessierungsschema - sieht doch gut aus 👍

**Comment by edjoha** [comment]
@Fuenfgeld sollen wir Grafiken, die im Wiki sind, im "Code" ablegen und im Wiki nur verlinken? Oder als .png direkt einfügen? Oder besser gesagt: Wie ist das üblich?

**Comment by Fuenfgeld** [comment]
Fügt sie ins Wiki ein

**Comment by Deronectes** [comment]
Sind im Wiki, und im Code, @edjoha kannst Du sie im Code bitte in einen Ordner sortieren? Nachdem Duschon weisst wie das geht über die Desktop App!

**Comment by Deronectes** [comment]
@edjoha Wie von Max geschrieben: Sie sind im Wiki und im Code, aber wie in dem anderen Issue schon geschrieben, wäre es schön wenn Du einen Folder für die vorhandenen Abbildungsdateien einrichten würdest
