### ISSUE TITLE
Link funktioniert nicht

### ISSUE THREAD

**Issue by edjoha** [Fuenfgeld/DMA2023TeamC#24]
der Link hinter "provider.csv" in der Quelldatendokumentation funktioniert nicht (@psokolo  Datensatz zu groß?)

**Comment by edjoha** [comment]
Vllt können wir dazu Max befragen, wie man das löst. Das Problem liegt bei Github, aber wie man das umgeht und trotzdem seine Daten zeigt, weiß ich nicht. Vielleicht im Zuge der Datenarchivierung, wenn wir die Daten öffentlich machen?

**Comment by Deronectes** [comment]
Ja, dass ist schon die ganze Zeit so, und bei einem Problem mit der Größe vielleicht eher kein Bug aber stattdessen ein Problem mit den Funktionen die uns zur Verfügung stehen in Github, oder?
Was wird öffentlich gemacht? Das fake Dataset?

**Comment by edjoha** [comment]
Ich finde das sollten wir Max fragen. Vllt heute Abend direkt

**Comment by psokolo** [comment]
bei mir funktioniert der Link problemlos..
der Inhalt wird halt nicht auf der Website gezeigt, dafür muss man den File herunterladen, weil er halt zu lang ist für GitHub. Aber das ist, denke ich, in ordnung

**Comment by edjoha** [comment]
Ah stimmt, das geht auch. Hab ich gar nicht gesehen. Ja, dann ist das sicher ok

**Comment by Deronectes** [comment]
Wir sollten uns entscheiden, bzw, uns auf die Aussage von Max beziehen wenn es diese Art der Verlinkung betrifft. Ich deine des noch immer hässlich und man macht ja kein Wiki, damit es später hässlich aussieht. Vielleicht gibt es noch einen anderen Weg. Können wir heute am Abend besprechen.

**Comment by edjoha** [comment]
Hier ging es um die verlinkte Tabelle. Das hat sich erledigt, da man es Downloaden kann und daher trotzdem Zugriff hat :)

**Comment by Deronectes** [comment]
War jetzt im falschen #, bei mir ist es als Kommentar zu #23 eingegangen, daher war ich ein wenig verwirrt.....
