### ISSUE TITLE
Pseudonymisierung der Patienten IDs

### ISSUE THREAD

**Issue by edjoha** [Fuenfgeld/DMA2023TeamC#27]

**Comment by edjoha** [comment]
@psokolo fertig? Oder muss das noch dokumentiert werden?

**Comment by psokolo** [comment]
nich habs schon dokumentiert auf der 'ETL Prozess' Wiki Seite, ich denke das ist fertig, wollte nur in Besprechung kurz fragen ob das richtig ist was ich gemacht habe

**Comment by psokolo** [comment]
ist abgeschlossen
