### ISSUE TITLE
Analyse der Daten bzgl unserer Fragestellung

### ISSUE THREAD

**Issue by edjoha** [Fuenfgeld/DMA2023TeamC#31]

**Comment by Deronectes** [comment]
Code und output werden für die Wiki auch benötigt, ist aber schon vorbereitet also kein neues Issue notwendig

**Comment by edjoha** [comment]
sehr gut

**Comment by edjoha** [comment]
@psokolo ist abgeschlossen, oder?

**Comment by psokolo** [comment]
ja, ich denke mehr brauchen wir nicht.. seid ihr mit den Grafiken und Ergebnissen einverstanden?

**Comment by edjoha** [comment]
ich ja. Ist wie besprochen. Mehr brauchen wir für unsere Fragestellung einfach nicht

**Comment by edjoha** [comment]
für die Dokumentation wurde ein neues issue erstellt #40
