### ISSUE TITLE
Mapping Tabellen erstellen

### ISSUE THREAD

**Issue by edjoha** [Fuenfgeld/DMA2023TeamC#33]

**Comment by edjoha** [comment]
@psokolo @Deronectes könnt ihr mal bitte gucken, ob das so passt?
@psokolo ich war mir tlw. nicht ganz sicher: 
1. manchmal hast du die "Field name" in Großbuchstaben geschrieben und manchmal nicht... ist das Absicht oder müssen wir das noch vereinheitlichen?
2. in "conditions_code" fehlt noch der Fremdschlüssel für Code, oder?

**Comment by psokolo** [comment]
1. Die meisten sind in Grossbuchstaben, denn in den Quelldaten sind die Spalten auch in Grossbuchstaben geschrieben, ich hab versucht das so zu lassen, wie es war und wie es in der DB bzw. in der DWH ist
2. Kann sein, ich guck das noch an

**Comment by Deronectes** [comment]
@edjoha Kannst Du das bitte ansehen, Du kannst ja auch die Änderungen vornehmen, in der Regel ist es mir gleich und wenn Du es gern einheitlich haben möchtest gern!

**Comment by edjoha** [comment]
wenn es original so ist, dann kann und sollte es natürlich so bleiben. deshalb frag ich lieber, bevor ich es ändere :)

**Comment by Deronectes** [comment]
@edjoha Warum? Das ergibt doch nicht wirklich Sinn, jedenfalls nicht für mich.

**Comment by Deronectes** [comment]
Dann können wir das jetzt zu machen. Wir können gern die Namen lassen wie sie sind, schöner ist vielleicht es zu vereinheitlichen. Das mit dem Fine-editing sollte aber vielleicht erst gemacht werden wenn wir fast alles fertighaben, gerade ist allerdings noch viel zu tun.

**Comment by edjoha** [comment]
ok
