### ISSUE TITLE
Sidebar Links und Wiki allgemein

### ISSUE THREAD

**Issue by edjoha** [Fuenfgeld/DMA2023TeamC#35]
Irgendwie blicke ich in unserem Wiki nicht mehr durch ... die Verlinkungen in der Sidebar enden jetzt teilweise auf leeren Pages oder sind auch manchmal falsch(?), kann das sein? Die Wiki Page "Quelldaten" scheint es nicht mehr zu geben, ist die entfernt? Oder umbenannt? Ich finde irgendwie vieles nicht wieder ... ist das nur anders?

**Comment by Deronectes** [comment]
Ja es sind leere Seiten da, weil die erst erstellt werden müssen. Ist eine Erinnerungshilfe bei dem was noch alles zu tun ist. 
@edjoha wir hatten darüber gesprochen, es ist nichts weg, nur einzele Tabellen im Sidebar ist unschön. Vielleicht wäre es ganz gut bei sowas eine Message in den Chat zu schreiben? Entschuldige, leider verwirren mich die vielen Issues.

**Comment by edjoha** [comment]
ok, wenn dir das hilft... ich kriege für den Chat halt keine Benachrichtigungen und dachte, so hat man alles beisammen.

Dann warte ich, bis du mit dem Wiki weitergekommen bist, so ergibt sich mir die Struktur irgendwie noch nicht... oder nicht mehr :)

**Comment by Deronectes** [comment]
Na ja, sieht ja ein wenig so aus als sei das mit dem Überblick nicht so wirklich klar. Kannst Du ja in

**Comment by Deronectes** [comment]
in einer Liste zusammenfassen, vielleicht können wir es dann gemeinsam ordnen, vielleicht hilft Dir das

**Comment by edjoha** [comment]
Ich muss das noch mal öffnen ... können wir da bitte morgen noch mal drübersprechen? ich finde wir haben nach wie vor Dopplungen drin und ich finde es immer noch lang und unübersichtlich. Habe mir Notizen gemacht, vllt können wir das morgen noch mal durchgehen

**Comment by Deronectes** [comment]
Sorry, wollte ich gar nicht schliessen, schon gar nicht nachdem ich das Issue gerade eingerichtet hatte
