### ISSUE TITLE
Lizenz ändern

### ISSUE THREAD

**Issue by edjoha** [Fuenfgeld/DMA2023TeamC#38]

**Comment by Deronectes** [comment]
@edjoha muss ich das verstehen? Hinter dem Link ist einfach ein Text zur Apache Lizenz, brauchen wir das? Und warum?

**Comment by edjoha** [comment]
ja, wir brauchen eine Lizenz. Ich habe das nachgelesen: ohne Lizenz, hast du auf deinen Code das Urheberrecht und niemand traut sich den anzufassen/zu nutzen/zu verändern. Du hattest im Wiki angelegt, dass wir eine CC License benutzen, aber das müssen wir noch mal ändern. Ich habe nachgelesen, dass empfohlen wird, CC nicht für Code zu benutzen. Deshalb habe ich jetzt MIT gewählt. Und die Apache rausgelöscht (die war voreingestellt bei der Erstellung des Repo)

**Comment by Deronectes** [comment]
Hast Du mal GNU angesehen? Das ist für code

**Comment by edjoha** [comment]
MIT auch ... soll ich das jetzt noch mal ändern? im Detail, also rechtlich, kenn ich mich damit auch nicht aus

**Comment by Deronectes** [comment]
Ja natürlich, dass muss unbedingt geändert werden (hihi)! Natürlich nicht, ich hatte vielleicht nur GNU erwartet..... Alles gut!

**Comment by edjoha** [comment]
Gut :) wir müssen es nur in der Dokumentation noch ändern. Weißt du auf Anhieb, wo du es eingefügt hast mit der CC License?

**Comment by Deronectes** [comment]
Im Datenmanagementplan

**Comment by edjoha** [comment]
wenn nicht, kann ich mich auch auf die Suche begeben

**Comment by edjoha** [comment]
also nur 1x?

**Comment by Deronectes** [comment]
nee, ist auch noch in der Beschreibung des Projekts unter 2. Datenmanagement

**Comment by edjoha** [comment]
ok im DMP ist es geändert

**Comment by Deronectes** [comment]
Ok, klingt ein bisschen gestelzt für mich, und so richtig sicher bin ich nicht ob das da Sinn ergibt, aber da können wir morgen noch drüber sprechen. Es geht doch auch nicht um ersetzen, sondern um Ergänzen, oder?

**Comment by edjoha** [comment]
Lizenz ist geändert

@Deronectes in der Dokumentation ist tlw immer noch die CC Lizenz drin, oder?

**Comment by Deronectes** [comment]
Ich habe noch zwei Stellen gefunden, dort habe ich die MIT Lizenz Info wqie besprochen eingefügt. Sollte damit überall geändert sein.

**Comment by edjoha** [comment]
super, dann schließe ich das Issue. Danke!

**Comment by Deronectes** [comment]
@edjoha Sorry ich habe ein weiteres Issue aufgemacht, weil dies schon geschlossen war. In jedem Fall muss die Lizenzinformation noch vervollständigt werden.

**Comment by Deronectes** [comment]
Leider habe ich es noch immer nicht raus wie ich zu den eigentlich Pages und files zurück komme die nach dem Umkopieren oder was auch immer nicht mehr zurückzuverfolgen sind. Da wir die Lizenzen schon drin hatten bräuchten wir nur zu der Version zurück die die beiden Lizenzen eingelschlossen haben

**Comment by Deronectes** [comment]
@edjoha 
Das mit der Licence ist doch gar kein Problem, eigentlich hatte ich es schon am Anfang nicht verstanden, oder hattest Du ausprobiert ob man nicht zwei licence files eintragen kann?

**Comment by edjoha** [comment]
der erkennt halt nur files mit exakt diesem Namen und du kannst ja nicht zwei Files mit dem gleichen Namen ablegen. Ich guck heute Abend mal, ich kann gerade nicht

**Comment by Deronectes** [comment]
Was Max angefragt hat geht einfach, im DMP waren ja mal beide Lizenzen drin, ist also einfach, ich sehe gleich mal nach ob ich an meine alten Version drankomme, oder ob das Sortieren auch dort die Revisionen vorher entfernt hat.

**Comment by Deronectes** [comment]
Ist leider beim Umkopieren wegegekommen und ich habe schon einiges probiert um die gelöschten Inhalte aufzurufen. @edjoha kannst Du mir sagen was Du gemacht hast? ich sehe in der Overall history auch einige der alten Seiten aber es ist fast unmöglich die Stelle zu finden zumal die das "Aufräumen" über umkopieren der Seiten scheinbar keine gute Idee ist. Ich weiss ist nicht deine Schuld, ich habe die Dokumente auch nur teilweise lokal als Schriftstücke abgelegt. Vielleicht doch nicht alles nur online ablegen, ich war aber davon ausgegangen, dass eigentlich nichts verloren gehen kann, scheint ja nicht so perfekt zu funktionieren.

**Comment by edjoha** [comment]
doch das findet man alles wieder. Ich schicke dir den Text der älteren version (incl. CC License) der Mail. Bitte die Seite nicht zu einer älteren Version zurücksetzen, da anschließend noch einiges an Korrekturen eingeflossen ist. Aber du kannst die entsprechenden Passagen ja rauskopieren und in der aktuellen Version der Page übernehmen

**Comment by Deronectes** [comment]
Danke für die Mail, wie hast Du den text gefunden, bzw. wie kann man all die altern Revisions sehen und nutzen, wenn sie mal in den Untiefen der History verschwunden sind!

**Comment by Deronectes** [comment]
Der Text ist auch irgendwie ziemlich blass, also ich würde das wieder eingeben müssen und auch die Links wieder erstellen, aber geht schon

**Comment by Deronectes** [comment]
Ja, ich sehe ja dass Du auf die vorherigen Versionen zugreifen kannst, aber noch immer nicht wie es geht, ich kann vergleichend die Seiten aufrufen, was nur bedingt hilfreich ist. Vielleicht ist es wieder mal nur eine kleine Sache die ich nicht gesehen habe.....

**Comment by edjoha** [comment]
du gehst auf revisions und dann rechts auf diese Zahlen/Buchstaben Codes

**Comment by Deronectes** [comment]
Und dann? Dann komme ich zur home seite, sonst passiert aber nichts. Ich sehe es mir nochmals an, wird schon irgendwann gehen. Aber wie ist das jetzt mit den Versionen vor dem Umkopieren, wie find ich die und wie weiss ich wwelche welche ist?

**Comment by edjoha** [comment]
ich kann es dir sonst noch mal zeigen. Danke fürs Einfügen der CC 4.0
