### ISSUE TITLE
Im code einen neuen Ordner anlegen für weitere Doku

### ISSUE THREAD

**Issue by Deronectes** [Fuenfgeld/DMA2023TeamC#39]

**Comment by Deronectes** [comment]
@psokolo Könntest Du das machen? Du hast ja auch einen neuen Ordner für die Analyse eingerichtet, ich kann das irgendwie nicht.

**Comment by psokolo** [comment]
klar, ist 'weitere Dokumentation' in Ordnung? welche bereits vorhandenen Files sollte ich da reintun?

**Comment by Deronectes** [comment]
Super, danke! Da sollten die files rein, die jetzt noch so in der Liste sind, ausser natürlich das README. Ist eigentlich allee Dokumentation, mehr oder weniger nützlich.

**Comment by psokolo** [comment]
ich würde sagen, ist abgeschlossen, oder?

**Comment by Deronectes** [comment]
jap! Danke, sieht gleich viel besser aus
