### ISSUE TITLE
Forschungsfrage

### ISSUE THREAD

**Issue by psokolo** [Fuenfgeld/DMA2023TeamC#4]
endgültig auswählen

**Comment by psokolo** [comment]
Inwieweit erhöht das metabolische Syndrom das Risiko für kardiovaskuläre Krankheiten? Gibt es auch einen Zusammenhang mit bestimmter Ethnie?

**Comment by Deronectes** [comment]
Das klingt gut. Ich würde nur gern wissen welche Untersuchungen oder Daten nützlich sind, um die Analyse auch durchführen zu können? +
Ich sende gleich mal was ich zum  DMP geschrieben habe, da ist natürlich zum Teil das Projekt beschrieben, bzw. die Darten die im Rahmen der Studie erhoben und gespreichert werden sollen. Per Mail ist gut?

**Comment by Deronectes** [comment]
Ist in der Projektbeschreibung aufgeführt

**Comment by edjoha** [comment]
dann kannst du es dort verlinken und schließen, oder?

**Comment by Deronectes** [comment]
Klar! Ich dachte das hätte ich schon

**Comment by Deronectes** [comment]
Damit dem Verlinken habe ich mir für alle Issues angesehen, hier ist die Aufgabe Forschungsfrage was, an verschiedenen Stellen erwähnt wird, es gibt, zumindest bis jetzt keine eigene Wiki-Seite für die Forschungsfrage.
