### ISSUE TITLE
WIKI Neue Stuktur

### ISSUE THREAD

**Issue by Deronectes** [Fuenfgeld/DMA2023TeamC#41]
@edjoha Warum hast Du alle Pages gelöscht? Die Links funktionieren nicht mehr und es sieht aus als hättest Du einfach alles gelöscht und in neue Pages umkopiert???? Warum? Die Herzchen finde ich etwas eigentartig

**Comment by Deronectes** [comment]
Dopplung im Sidebar gelöscht.

**Comment by edjoha** [comment]
nein, ich habe keine Pages gelöscht. nur eine auf zwei aufgeteilt, um die Projektbeschreibung und das Datenmanagement zu trennen. Dadurch haben wir nicht so viel doppelt. Die Sidebar ist noch nicht fertig, da bin ich gerade dran. Eine Page habe ich umbenannt, leider. Das war dumm, aber das habe ich erst hinterher gemerkt. Ich bin dabei, die Links überall zu aktualisieren, mach dir da keine Sorgen. Das korrigiere ich noch.

**Comment by edjoha** [comment]
> Dopplung im Sidebar gelöscht.

warum gefällt dir der DMP als Unterpunkt des Datenmanagement nicht? Ich finde wir haben am wenigsten Redundanzen, wenn wir unter Datenmanagement alles zusammenfassen: allgemeine Erläuterungen, wie FAIR Kriterien und Datenlebenszyklus, DMP und unser Datenhandling bzw die Analyse. Deshalb hatte ich es so verändert. Ihr hattet doch im Meeting zugestimmt, dass die Sidebar übersichtlicher werden muss...?

**Comment by Deronectes** [comment]
Doch, die Seiten sind weg, die Seiten die Du neu eingerichtet hast haben dann eine Revision und lassen die Nachverfolgbarkeit nicht zu, sondern nur so, wie es mit dem Page war, dass ich ungewollt zum Verschwinden gebracht habe. 
Das mit dem Datenmanagement sah ja noch so aus wie vorher, nur die Seit Im Allgemeinen habe ich gelöscht, erstmal ist der Titel nicht sehr aussagekräftig und dann ist es auch noch so, das es eine Dopplung von Datenamanagement war

**Comment by Deronectes** [comment]
So ist es auf jeden Fall übersichtlicher, denke ich

**Comment by edjoha** [comment]
so wie du es gerade geändert hast? Aber jetzt gehört der DMP nicht mehr zum Datenmanagement ... dafür aber die Datenprozessierung zum DMP. Das ergibt für mich keinen Sinn ... ist das so und verstehe ich das falsch?

**Comment by edjoha** [comment]
welche Seite vermisst du denn? Es ist nichts weg

**Comment by Deronectes** [comment]
Ist ja schon ein eigener Punkt, vielleicht besser das mit verschieden großen Überschriften zu machen? Dann können wir alles mit Daten unter dem Datenmanagement haben??? Sieht dann sicher eindeutig aus und ist ordentlich

**Comment by edjoha** [comment]
Datenmanagement ist ein Überpunkt. Und der link hinter "Im allgemeinen" ging zum ersten Punkt UNTER Datenmanagement. Aber gut, dann lassen wir es jetzt so, wenn es irritiert.

**Comment by edjoha** [comment]
> Ist ja schon ein eigener Punkt, vielleicht besser das mit verschieden großen Überschriften zu machen? Dann können wir alles mit Daten unter dem Datenmanagement haben??? Sieht dann sicher eindeutig aus und ist ordentlich

ja, das macht für mich auch Sinn. ich dachte so hatte ich es auch gemacht. Dann ist es doch gut so

**Comment by Deronectes** [comment]
Die Seiten sind da, aber Du hast sie in neue umkopiert, so dass die Revisions alle weg sind.

Das mit im Allgemeinen ist nicht gut finde ich, da die gleicht Informationen unter dem Punkt Datenmanagement sind und auch als überbegriff dann genau die Daten enthält

**Comment by edjoha** [comment]
vermisst du jetzt explizit eine Page? ansonsten können wir das issue ja wieder schließen. Wie gesagt, die Links korrigiere ich noch, da mach dir mal erstmal keinen Kopf drum. Solange wie die Pages an sich fertig sind und der Text vollständig, korrigiere ich alles nach und nach und du kannst dich gern unserem Skript für den Vortrag widmen

**Comment by edjoha** [comment]
> Die Seiten sind da, aber Du hast sie in neue umkopiert, so dass die Revisions alle weg sind.

Das korrigiere ich noch.

> Das mit im Allgemeinen ist nicht gut finde ich, da die gleicht Informationen unter dem Punkt Datenmanagement sind und auch als überbegriff dann genau die Daten enthält

das lassen wir jetzt so, alles gut

**Comment by Deronectes** [comment]
Aber sie sind wie neu, also nur mit den Änderungen die ich gerade eben gemacht habe, so als seien sie neu angelegt worden. Komisches Github, das mit dem logging verstehe wer will

**Comment by Deronectes** [comment]
Sorry, habe das wieder geöffnet, ich denke ist ein gutes Issue um die Fragen hier kurz zu besprechen. Der Name ist nicht so richtig treffend, alles was nun mit neuen Seiten und deren Positionierung können wir hier besprechen. Wo ist denn eigentlich die Datenschutzfolgeabschätzung?

**Comment by edjoha** [comment]
Achso ok.

die ist noch nicht im Sidebar. Wie gesagt, ich bin noch nicht fertig. Wo hättest du sie denn gern?

**Comment by Deronectes** [comment]
Vielleicht als Link im DMP als eine Art Anhang? Da könnten dann vielleicht auch noch links zu den Metadatenfiles rein, damit es nicht so einsam ist.

**Comment by edjoha** [comment]
Gehört es denn zum DMP? Ich dachte, das wäre ein eigenes "Dokument"? Sonst lege ich es einfach als dritten Punkt unter Datenmanagement an. 

Die Metadaten kommen ganz nach unten zu Reproduzierbarkeit. Sonst haben wir es wieder doppelt.

**Comment by edjoha** [comment]
soll die Datenarchivierung eigentlich unter Reproduzierbarkeit, oder lieber unter Datenprozessierung als Punkt 6? @psokolo was denkst du, wo es besser reinpasst?

**Comment by Deronectes** [comment]
Nee, die Metadaten sind Teil der Dokumentation und ich würde hier nicht so strikt sein mit der Dopplung. 
Mit der Datenschutz..... Bin ich nicht sicher, hast Du mal bei den anderen geguckt?

**Comment by edjoha** [comment]
ja, da ist alles überhaupt nicht so hierarchisch. Deshalb würde ich das auch nicht so strikt machen und einfach alles unter Datenmanagement ablegen

**Comment by edjoha** [comment]
die Metadaten sind doch schon im DMP, sogar in der Sidebar verlinkt

**Comment by Deronectes** [comment]
Als eigenen Punkt? geht auch und ist vom Arbeitsaufwand auf jeden Fall einen eigenen Unterpunkt wert ;-))

**Comment by Deronectes** [comment]
Stimmt

**Comment by edjoha** [comment]
> Als eigenen Punkt? geht auch und ist vom Arbeitsaufwand auf jeden Fall einen eigenen Unterpunkt wert ;-))

das hab ich auch gesehen :D krass, sieht echt gut aus

**Comment by Deronectes** [comment]
Der Link Datendokumentation im DMP führt zu einer leeren Seite?? Ich verlinke das mal mit dem entsprechenden Punkt im DMP weiter unten, sollten passen, oder haben wir ein eigenes Dokument dafür bzw. Page

**Comment by edjoha** [comment]
wie gesagt, die Links gehe ich noch mal durch am Ende

**Comment by Deronectes** [comment]
Alles klar, danke!

**Comment by edjoha** [comment]
Sagt mal, die Datendokumentation und Quelldatendokumentaion ist jetzt eigentlich doppelt. Ich würde eine der beiden Pages entfernen (und korrigiere natürlich alle links,... könnte aber bisschen dauern).

Frage: brauchen wir diese Metadaten-Tabelle wirklich? Ich weiß, die hat Arbeit gemacht, aber dann müssten wir konsequent auch die Versionen verlinken und irgendwo ablegen (haben wir das?) und eigentlich ist das alles nicht nötig, wenn wir sagen: Github hat eine Versionskontrolle

**Comment by edjoha** [comment]
ich würde gern einfach nur den Link zur PDF drinlassen (xlsx muss auch raus, weil es interoperabel ist)

**Comment by edjoha** [comment]
nicht interoperabel

**Comment by Deronectes** [comment]
Ja, der Excel file kann raus, nur der XMl ist wichtig und den PDF könnte ich im Code hinterlegen, so dass man ihn auch verlinken kann?! Soll ich das versuchen?

**Comment by Deronectes** [comment]
Vielleicht ein bisschen vorsichtig mit dem Rauswerfen, manchmal ist es nicht so schlecht die Sachen mehrfach zu haben, weil es an bestimmten Stellen erwartet wird.

**Comment by edjoha** [comment]
> Ja, der Excel file kann raus, nur der XMl ist wichtig und den PDF könnte ich im Code hinterlegen, so dass man ihn auch verlinken kann?! Soll ich das versuchen?

kannst du gern machen

**Comment by Deronectes** [comment]
https://github.com/Fuenfgeld/DMA2023TeamC/blob/main/Dokumentation/Metadata_MetaHeart_Study_2023_V1.pdf

**Comment by Deronectes** [comment]
Das ist der Link zur Doku im Code

**Comment by edjoha** [comment]
> Vielleicht ein bisschen vorsichtig mit dem Rauswerfen, manchmal ist es nicht so schlecht die Sachen mehrfach zu haben, weil es an bestimmten Stellen erwartet wird.

ich wüsste gerade nicht wo es nötig ist. Eigentlich überlappt sich immer nur alles inhaltlich etwas mit dem DMP, aber den haben wir eh extra ... und die Metadaten haben auch eine eigene Page (soll ich die Tabelle da reinkopieren?)

**Comment by Deronectes** [comment]
Excel file ist gelöscht

**Comment by edjoha** [comment]
aber deshalb frage ich ja, bevor ich es mache ;) nur ist es so eher verwirrend, dass es zwei Seiten gibt, mit nahezu dem gleichen Inhalt

**Comment by Deronectes** [comment]
Das meine ich im DMP ist das zu erwarten und dort hoffentlich im Kontext eingeordnet.

**Comment by edjoha** [comment]
ja mit dem DMP überschneidet sich das nicht. Da müsste ich dann vermutlich nur den link aktualisieren

**Comment by Deronectes** [comment]
Scheint ein wenig so als würden die DMPs immer mehr zu standardisierten Dokus, heisst aber nicht, dass man alles weglassen kann, nur weil es dort ist. Sonst muss man immer den DMP nach den Informationen durchforsten

**Comment by edjoha** [comment]
also kann die Tabelle weg? oder auf die Metadaten page?

**Comment by Deronectes** [comment]
Ok, ich weiss gerade nicht wo Du bist, leider muss ich gerade unterbrechen

**Comment by Deronectes** [comment]
Meinetwegen kann sie weg, ist auch nicht so furchtbar schön

**Comment by Deronectes** [comment]
Also die Tabelle

**Comment by edjoha** [comment]
alles klar

ich unterbreche auch erstmal

**Comment by Deronectes** [comment]
Ich habe noch einige Links gefixed, irgendwie scheinen sich doch einige "verschoben" zu haben, vermutlich durch das umkopieren, so dass die neuen Pages einen anderen Link haben??

**Comment by Deronectes** [comment]
Das mit den Emojis und neckischen kleinen Icons im Text sollten wir nochmal überdenken, zumal es bei manchen nicht so passt, also z.B. das Zeichen für Recycling als Reuse, sieht eher nach im Müll wühlen aus als nach Nachnutzung. Wir können die Icons gern drin lassen wenn das heute so gemacht werden kann, nur so richtig gut finde ich sie an einigen Stellen nicht.

**Comment by edjoha** [comment]
Wenn du damit nicht leben kannst, mach sie halt wieder weg. Ich fand, dass es unser Home auflockert, von anderen abhebt und ansprechender macht. Die Frage ist halt, ob es so schlimm ist, dass es wieder weg muss, oder ob uns dieses Hin und Her nur Zeit stiehlt und eigentlich keinen Unterschied macht. Ich dachte es geht auch darum, mit dem Github und dem Markdown etc. rumzuspielen.

**Comment by Deronectes** [comment]
Na ja die Herzchen sind sehr grenzwertig, und vielleicht ein bisschen sehr verspieltes Github. Aber noch etwas anderes: Wo ist die Dokumentation der Pseudomysierung??

**Comment by edjoha** [comment]
https://github.com/Fuenfgeld/DMA2023TeamC/wiki/ETL--Prozesses#pseudonymisierung-der-ids-der-patienten

**Comment by Deronectes** [comment]
Ok, ich habe irgendwie einen Link gesucht, aber ist sowieso schon wild verlinkt. Übrigens halt ich Verlinkiúngen die "hier" heissen problematisch, und es tut ja nichts wenn man benennt wohin der link geht, soll ja keine Überraschung werden

**Comment by Deronectes** [comment]
Danke euch fürs Durchsehen, beim Schreiben sieht man irgendwann nicht mehr was nicht ganz in Ordnung ist, bei einigen Sachen bin ich nicht sicher, ich habe manchmal etwas anderes gemeint, aber da es so komplex ist die alten Versionen zu recovern, und kein Versionsvergleich möglich ist, ist alles gut so wie es ist, und ich denke es ist nun auch nicht mehr die Zeit da was zu diskutieren. Ich danke euch jedenfalls für die mühsame Arbeit beim Durchsehen und Korregieren!
