### ISSUE TITLE
Lizenzbeschreibung

### ISSUE THREAD

**Issue by Deronectes** [Fuenfgeld/DMA2023TeamC#42]
@edjoha Bitte die MIT Lizenz beschreiben, bei CC ist das relativ einfach gewesen, keine Ahnung wie es bei MIT ist, ich denke aber Du hast die Info. Sollte eine sein, die die Rechte schützt aber die Bearbeitung des Codes erlaubt solange es angegeben ist, dass es eine Modifiktion ist.

**Comment by edjoha** [comment]
wo soll das rein? unter "Reproduzierbarkeit" steht schon was dazu

**Comment by Deronectes** [comment]
Keine Ahnung, auf jeden Fall ist es nicht gut, dass man bei dem Link auf der MIT licence auf keine Seite kommt.

**Comment by edjoha** [comment]
hier wäre die Website https://choosealicense.com/licenses/mit/ aber ich weiß nicht wirklich wo das jetzt rein soll. Eigentlich steht in dem LICENSE file alles drin und das ist ja immer verlinkt ...

**Comment by edjoha** [comment]
erledigt
