### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/DMA2023TeamC#43]
- Bitte bei den Lizenzen zwischen Code Lizenz und Daten Lizenz unterscheiden. Beides sollte explizit im DMP erwähnt werden.
- 
![image](https://user-images.githubusercontent.com/32547123/222404801-ba23ccb2-45fa-483d-81e7-e7f7c03f701c.png)
Bitte nur fiktive namen benutzen. Das gilt auch für die Uni Heidelberg. Ich will nicht dass das dekanat eine email bekommt ;).
Habt ihr das selbst geschrieben? wenn nicht unterliegt eine DSVA templates auch dem Urheberrecht passt da auf.
- Bitte setzt links zu dem code block im Colabbook in die Figure description.
- 
![image](https://user-images.githubusercontent.com/32547123/222405901-9fa21cf3-7a6d-47e9-b27f-3c60f85b0276.png)

**Comment by Deronectes** [comment]
Sind selbstverständlich alles ausgedachte Namen!

**Comment by Deronectes** [comment]
@edjoha Doch zwei Lizenzen, MIT und mit CC sollten es in Ordnung sein, hatte ich ja schon mal drin. Bei mir hat das leider nicht geklappt auf die Versionen zurückzugreifen bevor Du zum Aufräumen die Pages umkopiert hast.

**Comment by Fuenfgeld** [comment]
> Sind selbstverständlich alles ausgedachte Namen!

![image](https://user-images.githubusercontent.com/32547123/222410005-30751287-4d06-4360-9c61-7f011e8b4127.png)
Das könnte eine adresse sein die funktioniert. Warum sind das eigentlich bilder?

**Comment by Deronectes** [comment]
@Fuenfgeld Hatte ich dann schon gesehen. Ist bereits geändert

**Comment by edjoha** [comment]
@Fuenfgeld wir hatten schon mal zwei Lizenzen drin, aber Github erkennt nur eine automatisch (die im LICENSE file), die auf der ersten Seite angezeigt wird ... wie lösen wir das? oder können wir beide in das LICENSE file schreiben?

**Comment by Fuenfgeld** [comment]
Es ist egal ob das github erkennt. Es ist nur wichtig das es im daten
management plan dokumentiert wird

**Comment by edjoha** [comment]
CC Lizenz überall ergänzt. Danke @Deronectes
