### ISSUE TITLE
Powerpoint

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/DMA2023TeamC#44]
![image](https://user-images.githubusercontent.com/32547123/223695731-1745728b-73b3-4617-a433-a92d46bac61c.png)
Hi könnt ihr eure Powerpoint bitte auf Github hochladen.
Danke

**Comment by Deronectes** [comment]
@Fuenfgeld Hi Max, ja gern, wo soll es denn hin?

**Comment by Fuenfgeld** [comment]
documentation und dann verlinken. Und in der Abbildung bitte die Rechtschreib Prüfung deaktivieren.

**Comment by Deronectes** [comment]
Done!

**Comment by Fuenfgeld** [comment]
Das ist nicht das orginal mit dem die Abbildung erzeugt wurde oder?

**Comment by Deronectes** [comment]
Bei mir nicht. Ich habe gerade nochmals nachgesehen.

**Comment by Deronectes** [comment]
Ich musst zwar ein wenig umkopieren, da es partout die Rechtschreibung nicht deaktivieren wollte, ist aber aus dem Orginalfile. Ich bin gerade nicht in D und habe nur diese Files zur Verfügung auf dem Rechner.
