### ISSUE TITLE
Keine Github Seite geht verloren

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/DMA2023TeamC#45]
![image](https://user-images.githubusercontent.com/32547123/224334356-88bb71ca-cc69-4dd6-bf55-a3aba0e3380c.png)

**Comment by Deronectes** [comment]
Habe ich auch nicht behauptet, was fehlt sind die Revisionen, Siehe Mail! Der Ton ist unpassend! Vielleicht ist es besser das angesprochene Problem zu erfassen als polemisch  Kommentare als Issue zu posten!
