### ISSUE TITLE
Create a database schema

### ISSUE THREAD

**Issue by psokolo** [Fuenfgeld/DMA2023TeamC#6]

**Comment by edjoha** [comment]
https://dbschema.com/database-designer/CSVFiles.html Nützliches Tool zur Erstellung des Schemas

**Comment by psokolo** [comment]
mir fällt gerade ein, der Index von der Tabelle Conditions könnte besser sein, und zwar anstatt von Description würde ich Code nehmen. Descriprion ist von Code abhängig und es sucht sich einfacher nach Code..

**Comment by Deronectes** [comment]
Ja, das scheint auch die einzige Tabelle zu sein, die für alle Patientengruppen anlegt wird

**Comment by edjoha** [comment]
needs to be updated

**Comment by edjoha** [comment]
kann das zu? Ich dachte erst, wir brauchen noch mal ein neues Schema, was nur unsere 2 Tabellen enthält, aber denkt ihr, das ist wirklich notwendig?

**Comment by Deronectes** [comment]
Ja, das hat sich überholt .....

**Comment by Deronectes** [comment]
Auch heute Abend, oder? Ist je nur eine Kleinigkeit und man kann es jeder
Zeit wieder öffnen.

**Comment by Deronectes** [comment]
@Hanna: Wo ist denn das Schema mit den Daten die am Ende für die Auswertung benötigt werden, ist die schon als Figure im Wiki?

**Comment by edjoha** [comment]
Zweites Schema (Star-Schema?) für den ETL Prozess erstellen

**Comment by edjoha** [comment]
updated scheme for DWH added
