### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by edjoha** [Fuenfgeld/DMA2023TeamC#7]
Können wir die Tabellen des DB Schemas mit den csv files verlinken? Gibt es weitere sinnvolle Links?

**Comment by Deronectes** [comment]
@Hanna, hast Du bei deiner Graphik einen Link gesetzt und in wie weit sollte der auch in Ergebnisse und Analysendokumentation eingefügt werden?

**Comment by edjoha** [comment]
die Grafik ist mit der Abbildung in Code verlinkt, ja. Den kannst du also jederzeit nutzen, wobei ich nicht glaube, dass es da noch mal rein muss
