### ISSUE TITLE
Datenbank Dokumentation

### ISSUE THREAD

**Issue by psokolo** [Fuenfgeld/DMA2023TeamC#8]
das fehlt noch:

Erstellen sie eine Seite Pro Tabelle. Diese Seite sollte folgende Informationen enthalten. 
SQL Create Statement
Tabelle mit folgenden Spalten
Spalten Bezeichnung,
Spalten Datentyp,
Spalten Inhaltsbeschreibung,
Gibt es für diese Spalte ein Index? Wenn ja was ist der Index Name, was ist der Index Typ
Ist diese Spalte über ein Foreign Key constraint mit einer anderen Tabelle verbunden? Wenn ja Link zu der anderen Tabellen Dokumentation.

**Comment by Deronectes** [comment]
Wie sieht es mit Ordnerhierarchien aus?

**Comment by Deronectes** [comment]
Transfer in documentation

**Comment by edjoha** [comment]
dieses Issue müsste eigentlich abgeschlossen sein, oder?

**Comment by Deronectes** [comment]
Nein, wir können das erst machen, wenn wir entgültig entschieden haben welche Analyse und Daten wir nutzen

**Comment by edjoha** [comment]
Aber das, was ganz oben steht, ist doch fertig... was genau fehlt denn?

**Comment by Deronectes** [comment]
Die Festlegung der Struktur, wie wir das diskutiert hatte mit Stern und Snowflake, also in welcher Weise die Daten geordnet sind in der DB. Oder habe ich verpasst, dass das schon gemacht ist. Da können wir heute am Abend drüber sprechen, das im Text zu beschreiben ist nicht trivial, vielleicht habe ich auch den Inhalt der Issues zu weit interpretiert?!

**Comment by edjoha** [comment]
Ah ok. dann mach ich dafür ein neues Issue auf, das gehört dann ja schon zum ETL Prozess und ich glaube (wenn ich die Stichpunkte da oben lese), dass das hier um die Quelldaten und UrsprungsDB ging
