### ISSUE TITLE
Datamanagementplan

### ISSUE THREAD

**Issue by Deronectes** [Fuenfgeld/DMA2023TeamC#9]
Informationen sammeln
daten structuren aufstellen
daten qualität prüfprotokoll

**Comment by Deronectes** [comment]
Bitte den DMP ansehen
Es fehlt noch die Ordnerstruktur, sonst ist alles eingetragen.

**Comment by Deronectes** [comment]
Sorry, just closed it involuntarily

**Comment by edjoha** [comment]
Ich würde sagen, dass der Aufbau etwas geordneter muss:
Home
Projektbeschreibung (also Zusammenfassung und Einleitung unter METAHEART_Projekt)
 - Zusammenfassung
 - Einleitung
Quelldaten
 -
 -
...
Datenmanagementplan (da muss die Grafik mit rein)
-
-
-
...
Ergebnisse

Mein Problem ist nur: kann man die Pages jetzt noch mal verschieben??

**Comment by Deronectes** [comment]
Sehe ich nicht so, als Teil des Wiki kann das Schema da rein, aber nicht in den Plan selbst. Hatten wir besprochen, oder?

**Comment by Deronectes** [comment]
Ist fertig
